In [1]:
!pip install sentence-transformers numpy scipy scikit-learn plotly

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.9 MB 9.6 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.9 MB 13.4 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.9 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 14.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 12.8 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from sentence_transformers import SentenceTransformer

# Load a pre-trained sentence embedding model
model_name = 'all-MiniLM-L6-v2'
model = SentenceTransformer(model_name)

print(f"Model '{model_name}' loaded successfully.")
# Output: Model 'all-MiniLM-L6-v2' loaded successfully.


Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Model 'all-MiniLM-L6-v2' loaded successfully.


In [5]:
import numpy as np

sentences = [
    "The delivery arrived on time.",
    "My package was delivered promptly.",
    "Vector databases store numerical representations.",
    "How can I optimize database queries?",
    "The weather today is sunny and warm."
]

# Generate embeddings for the sentences
embeddings = model.encode(sentences)

# Check the dimensions of the embeddings
print(f"Shape of embeddings matrix: {embeddings.shape}")


# Display the first few dimensions of the first embedding
print(f"First 5 dimensions of the first sentence embedding:\n{embeddings[0, :5]}")
# Output: First 5 dimensions of the first sentence embedding:


Shape of embeddings matrix: (5, 384)
First 5 dimensions of the first sentence embedding:
[-0.05027558  0.04267898 -0.01072991  0.04200416  0.01438534]


In [6]:
from scipy.spatial.distance import cosine
num_sentences = len (sentences)
similarity_matrix = np.zeros((num_sentences,num_sentences))
for i in range(num_sentences):
    for j in range(num_sentences):
        similarity = 1 - cosine(embeddings[i],embeddings[j])
        similarity_matrix[i,j] = similarity
print("Pairwise Cosine Similarity Matrix:")
print(np.round(similarity_matrix,2))

Pairwise Cosine Similarity Matrix:
[[ 1.    0.7   0.    0.03  0.15]
 [ 0.7   1.    0.03  0.09  0.12]
 [ 0.    0.03  1.    0.27 -0.01]
 [ 0.03  0.09  0.27  1.    0.04]
 [ 0.15  0.12 -0.01  0.04  1.  ]]


In [1]:
from sklearn.decomposition import PCA
import plotly.graph_objects as go

# Reduce dimensions to 2D using PCA
pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

# Create a scatter plot (using pre-calculated example coordinates for consistency)
# Replace these coordinates with the actual output of your PCA transformation
# if you run the code yourself.
example_coords = {
    "x": [-0.15, -0.18, 0.10, 0.25, -0.02],
    "y": [0.08, 0.10, -0.05, -0.12, 0.01]
}

fig = go.Figure(data=go.Scatter(
    # x=embeddings_2d[:, 0], # Use actual PCA output
    # y=embeddings_2d[:, 1], # Use actual PCA output
    x=example_coords["x"], # Using example values
    y=example_coords["y"], # Using example values
    mode='markers+text',
    marker=dict(
        size=10,
        color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'], # Example colors
        opacity=0.8
    ),
    text=[f"'{s[:20]}...'" for s in sentences], # Display shortened text labels
    textposition='top center'
))

fig.update_layout(
    title='2D PCA Projection of Sentence Embeddings',
    xaxis_title='Principal Component 1',
    yaxis_title='Principal Component 2',
    width=700,
    height=500,
    showlegend=False
)

# To display the plot (e.g., in a Jupyter Notebook or save to HTML)
fig.show()

NameError: name 'embeddings' is not defined